---
- name: update resolve.conf
  shell: |
    mv /etc/resolv.conf  /etc/resolv.conf.bak
    ln -s /run/systemd/resolve/resolv.conf /etc/
    systemctl restart systemd-resolved.service && systemctl enable systemd-resolved.service
  tags: pull

- name: create BOOTSTRAP_TOKEN
  shell: |
    com=`awk -F , '{print$1}' "{{ ansible_dir }}/roles/master/files/token.csv"`
    BBOOTSTRAP_TOKEN=$com

- name: create directory
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ k8s_dir}}/ssl"
    - /var/lib/kubelet
    - /var/lib/kube-proxy

- name: copy certificate
  copy:
    src: "{{ item }}"
    dest: "{{ k8s_dir }}/ssl"
  loop:
    - ca.pem
    - ca-key.pem
    - kube-proxy.pem
    - kube-proxy-key.pem

- name: copy components
  copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}"
    mode: 0755
  loop:
    - kubelet
    - kube-proxy

- name: copy kubconfig 
  template:
    src: "{{ item }}"
    dest: "{{ k8s_dir }}/{{ item.split('.')[:-1]|join('.') }}"
  loop:
    - kubelet.json.j2
    - kube-proxy.yaml.j2
    - kube-proxy.kubeconfig.j2
    - kubelet-bootstrap.kubeconfig.j2

- name: copy service
  template:
    src: "{{ item }}"
    dest: "/usr/lib/systemd/system/{{ item.split('.')[:-1]|join('.') }}"
  loop:
    - kubelet.service.j2
    - kube-proxy.service.j2

- name: enabled service
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  loop:
    - kubelet
    - kube-proxy

- name: ctr load img
  shell: |
    for i in cni node kube-controllers pod2daemon-flexvol
      do
        ctr -n k8s.io i pull registry.cn-shanghai.aliyuncs.com/asvex/$i:v3.22.2
        ctr -n k8s.io i tag registry.cn-shanghai.aliyuncs.com/asvex/$i:v3.22.2 docker.io/calico/$i.v3.22.2
        ctr -n k8s.io i rm registry.cn-shanghai.aliyuncs.com/asvex/$i:v3.22.2
    done
    ctr -n k8s.io i pull registry.aliyuncs.com/google_containers/coredns:1.8.7
    ctr -n k8s.io i tag registry.aliyuncs.com/google_containers/coredns:1.8.7 docker.io/coredns/coredns:v1.8.7
    ctr -n k8s.io i rm registry.aliyuncs.com/google_containers/coredns:1.8.7
