---
- name: tar etcd-v3.5.0-linux-amd64.tar.gz
  unarchive:
    src: etcd-v3.5.0-linux-amd64.tar.gz
    dest: "{{ work_dir }}"
    extra_opts:
      - --strip-components=1

- name: copy etcd{,ctl}
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_dir }}/roles/etcd/files"
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ work_dir }}/etcd"
    - "{{ work_dir }}/etcdctl"

- name: create token.csv
  shell: |
    cat > {{ ansible_dir }}/roles/master/files/token.csv << EOF
    $(head -c 16 /dev/urandom | od -An -t x | tr -d ' '),kubelet-bootstrap,10001,"system:kubelet-bootstrap"
    EOF

- name: tar kubernetes-server-linux-amd64.tar.gz
  unarchive:
    src: kubernetes-server-linux-amd64.tar.gz
    dest: "{{ work_dir }}"
    extra_opts:
      - '--strip-components=3'

- name: copy kube{ctl,-apiserver,-controller-manager,-scheduler}
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_dir }}/roles/master/files"
    mode: 0755
  loop:
    - "{{ work_dir }}/kubectl"
    - "{{ work_dir }}/kube-apiserver"
    - "{{ work_dir }}/kube-controller-manager"
    - "{{ work_dir }}/kube-scheduler"

- name: copy kube{let,-proxy}
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_dir }}/roles/node/files"
    mode: 0755
  loop:
    - "{{ work_dir }}/kubelet"
    - "{{ work_dir }}/kube-proxy"
